### ISSUE TITLE
Use devfile structs from devfile/api

### ISSUE THREAD

**Issue by ranakan19** [devfile/library#26]
### Is your task related to a problem? Please describe.
There are already struct defined that are representing devfile in https://github.com/devfile/api
and is currently the main source of truth for devfile schema.

### Describe the solution you'd like
Library should be using the structs defined in kubernetes-api to represent the devfile instead of having defined new structs.

### Describe alternatives you've considered
---NA--

### Additional context
This whole [repo](https://github.com/devfile/kubernetes-api/blob/2b9600bd1c050619cb35a9cbe749a280d169dc33/pkg/apis/workspaces/v1alpha1/devworkspaceTemplateSpec.go#L5) defines DevWorkspace CRD, and devfile is essentially a subset of DevWorkspace.

**Comment by yangcao77** [comment]
I'm closing this issue as it's already done.
